language: java
install: true
script:
  - openssl aes-256-cbc -d -in key.gpg.enc -out key.gpg -k "$OPENSSL_PWD"
  - gpg --import key.gpg
  - gradle dependencies
  - gradle verifyGoogleJavaFormat
  - gradle check
  - gradle test
  - gradle release -Prelease.useAutomaticVersion=true
