language: java
install: true
script:
  - openssl aes-256-cbc -d -in key.gpg.enc -out $GPG_FILE -k "$OPENSSL_PWD"
  - gpg --import $GPG_FILE
  - gradle dependencies
  - gradle verifyGoogleJavaFormat
  - gradle check
  - gradle test
  - gradle release -Prelease.useAutomaticVersion=true
